### ISSUE TITLE
RFC: TDesign Omi Roadmap

### ISSUE THREAD

**Issue by ChelesteWang** [Tencent/omi#783]
## Task List

- [ ] Implementation development TDesign Omi CLI 
- [ ] Tdesign Omi document infrastructure improved
- [ ] The Button component Omiu was migrated to Tdesign

**Comment by ziMu-66ccff** [comment]
你好，我想先领取一下，input，radio，select，switch，loading这几个组件

**Comment by ChelesteWang** [comment]
Demo 

```js
我想先领取一下，input，radio，select，switch，loading这几个组件

## Task Progress
- [ ] input  
- [ ] radio，
- [ ] select，
- [ ] switch，
- [ ] loading
```

**Comment by Evan-WH** [comment]
我想先领取一下tag，Image这俩组件

**Comment by GuYith** [comment]
领取link，space，divider，dropdown，rate

## Task Progress
- [ ] link #775 
- [ ] space，
- [ ] divider，
- [ ] dropdown，
- [ ] rate

**Comment by icy-blue** [comment]
你好，我想先领取一下card这个组件

## Task Progress
- [ ] card

**Comment by sami-jiaze** [comment]
你好，我想先领取一下layout这个组件
## Task Progress
- [ ] layout

**Comment by Qjstar** [comment]
我想先领取一下message这几个组件

## Task Progress
- [ ] message

**Comment by Tomwillan** [comment]
你好，我认领form组件
```js
- [ ]  form
```

**Comment by DreamerAndStriver** [comment]
你好，我想认领Button组件

**Comment by ChelesteWang** [comment]
> 你好，我想认领Button组件

Button 已经有人认领了

**Comment by Game-Lover-JYH** [comment]
> ## 任务列表
> ### 常见
> * [ ] 实施开发 易信近江CLI
> * [ ] Tdesign Omi 文档基础结构得到改进
> * [ ] 设计码盒 道信码盒实施与优化
> 
> ### 组件
> * [ ] 按钮
> * [ ] 输入
> * [ ] 拾取器
> * [ ] 收音机
> * [ ] 滑 块
> * [ ] 开关
> * [ ] 链接
> * [ ] 图标
> * [ ] 分
> * [ ] 网 格
> * [ ] 布局
> * [ ] 空间
> * [ ] 词缀
> * [ ] 锚
> * [ ] 背顶
> * [ ] 面包屑
> * [ ] 下拉列表
> * [ ] 菜单
> * [ ] 分页
> * [ ] 步骤
> * [ ] 粘性工具
> * [ ] 制表符
> * [ ] 自动完成
> * [ ] 级联
> * [ ] 复选框
> * [ ] 颜色选择器
> * [ ] 日期选择器
> * [ ] 形式
> * [ ] 输入
> * [ ] 输入装饰
> * [ ] 输入编号
> * [ ] 标签输入
> * [ ] 收音机
> * [ ] 范围输入
> * [ ] 选择
> * [ ] 选择输入
> * [ ] 文本区域
> * [ ] 转移
> * [ ] 时间选择器
> * [ ] 树选择
> * [ ] 上传
> * [ ] 化身
> * [ ] 徽章
> * [ ] 日历
> * [ ] 卡
> * [ ] 崩溃
> * [ ] 评论
> * [ ] 图像
> * [ ] 图像查看器
> * [ ] 列表
> * [ ] 装载
> * [ ] 进展
> * [ ] 骨架
> * [ ] 刷卡器
> * [ ] 桌子
> * [ ] 泰格埃文-WH
> * [ ] 时间轴
> * [ ] 工具提示
> * [ ] 树
> * [ ] 水印
> * [ ] 率
> * [ ] 警报
> * [ ] 对话
> * [ ] 抽屉
> * [ ] 指导
> * [ ] 消息
> * [ ] 通知
> * [ ] 弹出确认
> * [ ] 弹出



> ## 任务列表
> ### 常见
> * [ ] 实施开发 易信近江CLI
> * [ ] Tdesign Omi 文档基础结构得到改进
> * [ ] 设计码盒 道信码盒实施与优化
> 
> ### 组件
> * [ ] 按钮
> * [ ] 输入
> * [ ] 拾取器
> * [ ] 收音机
> * [ ] 滑 块
> * [ ] 开关
> * [ ] 链接
> * [ ] 图标
> * [ ] 分
> * [ ] 网 格
> * [ ] 布局
> * [ ] 空间
> * [ ] 词缀
> * [ ] 锚
> * [ ] 背顶
> * [ ] 面包屑
> * [ ] 下拉列表
> * [ ] 菜单
> * [ ] 分页
> * [ ] 步骤
> * [ ] 粘性工具
> * [ ] 制表符
> * [ ] 自动完成
> * [ ] 级联
> * [ ] 复选框
> * [ ] 颜色选择器
> * [ ] 日期选择器
> * [ ] 形式
> * [ ] 输入
> * [ ] 输入装饰
> * [ ] 输入编号
> * [ ] 标签输入
> * [ ] 收音机
> * [ ] 范围输入
> * [ ] 选择
> * [ ] 选择输入
> * [ ] 文本区域
> * [ ] 转移
> * [ ] 时间选择器
> * [ ] 树选择
> * [ ] 上传
> * [ ] 化身
> * [ ] 徽章
> * [ ] 日历
> * [ ] 卡
> * [ ] 崩溃
> * [ ] 评论
> * [ ] 图像
> * [ ] 图像查看器
> * [ ]  List
> * [ ]  Loading @ziMu-66ccff
> * [ ]  Progress
> * [ ]  Skeleton
> * [ ]  Swiper
> * [ ]  Table
> * [ ]  Tag @Evan-WH Evan-WH
> * [ ]  Timeline
> * [ ]  Tooltip
> * [ ]  Tree
> * [ ]  Watermark
> * [ ]  Rate @GuYith
> * [ ]  Alert
> * [ ]  Dialog
> * [ ]  Drawer
> * [ ]  Guide
> * [ ]  Message @Qjstar
> * [ ]  Notification
> * [ ]  Popconfirm
> * [ ]  Popup

**Comment by Game-Lover-JYH** [comment]
Popconfirm

**Comment by YingqianChen** [comment]
你好，我想领取一下Badge组件

## Task Progress
- [ ] Badge

**Comment by DreamerAndStriver** [comment]
> > 你好，我想认领Button组件
> 
> Button 已经有人认领

> > 你好，我想认领Button组件
> 
> Button 已经有人认领了

噢噢，那我要avator组件

**Comment by Summer-Shen** [comment]
您好，我想先领取下
- Slider
- Breadcrumb
- Steps
- Checkbox
- ColorPicker
- Radio
感谢！

**Comment by ChelesteWang** [comment]
> 您好，我想先领取下
> 
> * Slider
> * Breadcrumb
> * Steps
> * Checkbox
> * ColorPicker
> * Radio
> 
> 感谢！

不建议领取过多，当前领取的也与之前的同学领取的有重合

**Comment by ChelesteWang** [comment]
> 你好，我想先领取一下，input，radio，select，switch，loading这几个组件

领取请勿超过3个

**Comment by Summer-Shen** [comment]
了解，那么我先领取下

- [ ] Slider
- [ ] Breadcrumb
- [ ] Checkbox

感谢！

**Comment by GaviXi** [comment]
你好，我想领取一下Picker组件
## Task Progress

- [ ] Picker

**Comment by Binks123** [comment]
你好，想领取Affix这个组件
## Task Progress
- [ ] Affix

**Comment by dntzhang** [comment]
> > 您好，我想先领取下
> > 
> > * Slider
> > * Breadcrumb
> > * Steps
> > * Checkbox
> > * ColorPicker
> > * Radio
> > 
> > 感谢！
> 
> 不建议领取过多，当前领取的也与之前的同学领取的有重合

只要能做完，领得越多越好:)

**Comment by suyufan** [comment]
你好，我想领取dialog TimePicker

**Comment by Summer-Shen** [comment]
> 了解，那么我先领取下
> 
> ## Task Progress
> * [ ]  Slider
> * [ ]  Breadcrumb
> * [ ]  Checkbox
> 
> 感谢！

好像 Slider 已经有人完成了，我再领取一个 ColorPicker，感谢~

**Comment by Qjstar** [comment]
> 我想加一个 Notification组件
> 
> ## Task Progress
> * [ ]  message
> * [ ]  Notification

**Comment by dntzhang** [comment]
@Qjstar 好

**Comment by GaviXi** [comment]
你好，我想加一个Textarea组件
## Task Progress

- [ ] Picker
- [ ] DatePicker
- [ ] Textarea

**Comment by GuYith** [comment]
> 

补充领取一个popup组件

**Comment by GuYith** [comment]
> 领取link，space，divider，dropdown，rate
> 
> ## Task Progress
> * [ ]  link [feature: TDesign link component #775](https://github.com/Tencent/omi/issues/775) [feat: add and init link component #777](https://github.com/Tencent/omi/pull/777) [feat: improve link component, add docs and examples #781](https://github.com/Tencent/omi/pull/781) [feat: link and divider site, fix children #786](https://github.com/Tencent/omi/pull/786)
> * [ ]  space [feat: add space #787](https://github.com/Tencent/omi/pull/787)  [feat: add space site and fix some bug #789](https://github.com/Tencent/omi/pull/789)
> * [ ]  divider [feat: add divider #785](https://github.com/Tencent/omi/pull/785) [feat: link and divider site, fix children #786](https://github.com/Tencent/omi/pull/786)
> * [ ]  dropdown
> * [ ]  rate

补充领取一个popup组件

**Comment by dntzhang** [comment]
@GuYith 棒

**Comment by DreamerAndStriver** [comment]
你好，我还想再领取一个comment组件

**Comment by dntzhang** [comment]
@DreamerAndStriver 好的

**Comment by GaviXi** [comment]
补充领取 BackTop组件和List组件
## Task Progress

- [ ] Picker 
- [ ] DatePicker
- [ ] Textarea https://github.com/Tencent/omi/issues/790
- [ ] BackTop https://github.com/Tencent/omi/issues/793
- [ ] List

**Comment by dntzhang** [comment]
@GaviXi 好的，👍

**Comment by MichaelYoung23** [comment]
你好，我想领取input组件
## Task Progress
- [ ] input

**Comment by MichaelYoung23** [comment]
你好，我想领取一下icon组件
## Task Progress
- [ ] icon

**Comment by dntzhang** [comment]
@MichaelYoung23 好的

**Comment by DreamerAndStriver** [comment]
你好，我想再领取input-adornment组件

**Comment by dntzhang** [comment]
@DreamerAndStriver  好

**Comment by GaviXi** [comment]
由于select组件需要依赖其他组件进行开发，现补充领取tag、tag-input、select-input
## Task Progress

- [ ] Select
- [ ] DatePicker
- [ ] Textarea https://github.com/Tencent/omi/issues/790  https://github.com/Tencent/omi/pull/802  https://github.com/Tencent/omi/pull/811  https://github.com/Tencent/omi/pull/830
- [ ] BackTop https://github.com/Tencent/omi/issues/793  https://github.com/Tencent/omi/pull/821  https://github.com/Tencent/omi/pull/824  https://github.com/Tencent/omi/pull/827
- [ ] List https://github.com/Tencent/omi/pull/795  https://github.com/Tencent/omi/pull/807  https://github.com/Tencent/omi/pull/820
- [ ] tag
- [ ] tag-input
- [ ] select-input

**Comment by dntzhang** [comment]
@GaviXi 好的

**Comment by MichaelYoung23** [comment]
你好，Radio一直没有pr，我想来完善，还有我想再领取menu组件
## Task Progress
- [ ] Radio
- [ ] menu

**Comment by dntzhang** [comment]
@MichaelYoung23 好的

**Comment by Qjstar** [comment]
> 我想再加一下Tooltip和Watermark组件
> 
> ## Task Progress
> * [ ]  Message
> * [ ]  Notification
> * [ ]  Tooltip
> * [ ]  Watermark

**Comment by dntzhang** [comment]
@Qjstar 好

**Comment by dntzhang** [comment]
@MichaelYoung23 好的

**Comment by rajendrakrshaw** [comment]
Assign me something
